# Generated by Django 3.2.5 on 2021-08-13 12:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('widget', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='StoreWidget',
            fields=[
                ('abstractbasewidget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='widget.abstractbasewidget')),
                ('download', models.IntegerField(default=0)),
                ('widget_type', models.CharField(choices=[('simple_widget_search_bar', '검색창'), ('simple_widget_d_day', '디데이'), ('simple_widget_note', '메모장'), ('simple_widget_finance', '주식'), ('simple_widget_book_mark', '북마크'), ('simple_widget_timer', '타이머'), ('layout_widget', '레이아웃 위젯')], default='layout_widget', help_text='위젯 형식', max_length=31)),
                ('description', models.CharField(blank=True, help_text='위젯 설명', max_length=255, null=True)),
                ('name', models.CharField(blank=True, help_text='위젯 제목', max_length=63, null=True)),
                ('is_removed', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='storewidgets/')),
                ('like_users', models.ManyToManyField(blank=True, related_name='like_widgets', to='account.User_info')),
            ],
            bases=('widget.abstractbasewidget',),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.comment')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user_info')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='image/defaultprofile.png', null=True, upload_to='images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.user_info')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='widget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='store.storewidget'),
        ),
        migrations.AddField(
            model_name='comment',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user_info'),
        ),
    ]
