# Generated by Django 3.2.5 on 2021-08-13 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractBaseWidget',
            fields=[
                ('seq', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='create_date')),
                ('data', models.TextField(default='[]')),
                ('from_store', models.BooleanField(default=False)),
                ('creater', models.ForeignKey(db_column='creater', on_delete=django.db.models.deletion.CASCADE, to='account.user_info')),
            ],
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('abstractbasewidget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='widget.abstractbasewidget')),
                ('is_applied', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=31)),
                ('image', models.ImageField(blank=True, null=True, upload_to='layouts/')),
                ('is_widget', models.BooleanField(default=False)),
                ('widget_type', models.TextField(null=True)),
                ('owner', models.ForeignKey(db_column='owner', on_delete=django.db.models.deletion.CASCADE, to='account.user_info')),
            ],
            bases=('widget.abstractbasewidget',),
        ),
    ]
